name: my_portfolio
description: A Flutter web portfolio inspired by Dribbble shot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  audioplayers: ^6.5.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.9.1
  google_fonts: ^5.0.0
  lottie: ^3.3.1
  url_launcher: ^6.2.5
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/flutter1.png
    - assets/supabase1.png
    - assets/github1.png
    - assets/p1.jpg
    - assets/p2.jpg
    - assets/wmountain.jpg
    - assets/ss1.jpg
    - assets/ss2.jpg
    - assets/ss3.jpg
    - assets/ss4.jpg
    - assets/bg.png
    - assets/lottie/Welcome.json

